import { Inter } from "next/font/google";

import "bootstrap/dist/css/bootstrap.css";
import Menu from "@/components/client/Menu";
import AuthProvider from "@/providers/AuthProvider";
import connectDB from "@/lib/connectDB";
import CartsProvider from "@/providers/cartsProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartsProvider>
          <AuthProvider>
            <Menu />
            {children}
          </AuthProvider>
        </CartsProvider>
      </body>
    </html>
  );
}
